version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "16"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    environment:
      DATABASE_URL: "mysql://root:dev@db:3306/nws-inventaire" # DEV URL DB
    network_mode: service:db
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysqldb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev

volumes:
  mysqldb-data: